
export const GET_USERS = "GET_USERS"
export const DELETE_USER = "DELETE_USER"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT"